# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notiecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('kcol', models.CharField(max_length=30)),
                ('vcol', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notieitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notiecardid', models.IntegerField(max_length=30)),
                ('kword', models.CharField(max_length=128)),
                ('val', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
