# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notiecard',
            name='kcol',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notiecard',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notiecard',
            name='vcol',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notieitem',
            name='kword',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='notieitem',
            name='notiecardid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notieitem',
            name='val',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
