# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171207_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardnoteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cardnotecardid', models.IntegerField()),
                ('kword', models.CharField(blank=True, max_length=128)),
                ('val', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Notiecard',
            new_name='CardnoteCard',
        ),
        migrations.DeleteModel(
            name='Notieitem',
        ),
    ]
