# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cardnotecard_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardnotecard',
            name='color',
        ),
        migrations.AddField(
            model_name='cardnotecard',
            name='category',
            field=models.CharField(blank=True, choices=[('danger', '红色'), ('warning', '橙色'), ('success', '绿色'), ('primary', '蓝色'), ('default', '灰色'), ('info', '浅蓝色')], default='default', max_length=20),
        ),
    ]
