# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171215_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardnotecard',
            name='category',
            field=models.CharField(blank=True, choices=[('default', '灰色'), ('primary', '蓝色'), ('info', '浅蓝色'), ('success', '绿色'), ('warning', '橙色'), ('danger', '红色')], default='default', max_length=20),
        ),
    ]
