# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171215_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardnotecard',
            name='userid',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardnotecard',
            name='category',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('primary', 'Primary'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='default', max_length=20),
        ),
    ]
