# Generated by Django 2.0.1 on 2018-01-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180105_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardnotecard',
            name='category',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='default', max_length=20),
        ),
    ]
