# Generated by Django 2.0.1 on 2018-02-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180112_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('userid', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField()),
                ('pv', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
