# Generated by Django 2.0.1 on 2018-09-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_shorturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='legal',
            field=models.NullBooleanField(default=None),
        ),
    ]
