# Generated by Django 2.0.7 on 2019-02-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_shorturl_legal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardnotecard',
            name='username',
        ),
    ]
